name: Publish static website to Azure Storage
on: push
- name: Azure Static Website Deploy
    uses: feeloor/azure-static-website-deploy@master
    with:
      SOURCE_DIR: "$web"
      AZURE_CLIENT_ID: "1128f95d-80ed-4f25-b94b-18a8dd40887d2"
      AZURE_TENANT_ID: "262b1ce8-a817-4a56-8626-66b5b6a20b35"
      AZURE_SECRET: ${{ secrets.AZURE_SECRET }}
      AZURE_SUBSCRIPTION_ID: "e6e5b570-5e59-4f89-989b-b2bef40a0e9f"
      AZURE_STORAGE_ACCOUNT_NAME: "dpbweb"
      AZURE_INDEX_DOCUMENT_NAME: "index.html"
      AZURE_ERROR_DOCUMENT_NAME: "error.html"
